/**
 * ContentPulse Plugin Types
 * PayloadCMS v3 Plugin for Semantic Decay & Freshness Analysis
 */

/**
 * Configuration options for the ContentPulse plugin
 */
export interface ContentPulseConfig {
  /** Collections to monitor for content decay (e.g., ['posts', 'articles']) */
  collections: string[]

  /** Minimum freshness score (0-100) before showing warnings. Default: 80 */
  warningThreshold?: number

  /** Maximum age in days before a date is considered stale. Default: 365 */
  maxAgeDays?: number

  /** Custom version patterns to detect (regex strings) */
  customVersionPatterns?: string[]

  /** Enable/disable specific decay analyzers */
  analyzers?: {
    dates?: boolean
    versions?: boolean
    custom?: boolean
  }
}

/**
 * Warning generated by the content analyzer
 */
export interface PulseWarning {
  /** Type of decay detected */
  type: 'date_decay' | 'version_decay' | 'custom'

  /** Severity level */
  severity: 'low' | 'medium' | 'high' | 'critical'

  /** Human-readable warning message */
  message: string

  /** The original text that triggered the warning */
  originalText: string

  /** Suggested replacement or action */
  suggestion?: string
}

/**
 * Analysis result from the content analyzer
 */
export interface PulseAnalysisResult {
  /** Freshness score from 0 (completely stale) to 100 (perfectly fresh) */
  score: number

  /** Array of detected warnings */
  warnings: PulseWarning[]

  /** Timestamp of when analysis was performed */
  analyzedAt: string
}
